### ISSUE TITLE
Create artwork such as logo and icon

### ISSUE THREAD

**Issue by intergrav** [MenacingPerson/forgified-Additive#2]
I can do this sometime. If you have any ideas, then feel free to list them here, but I'll probably make the icon similar to Adrenaline and the other modpacks

**Comment by intergrav** [comment]
This is what I have so far

![image](https://github.com/skywardmc/drill/assets/42325132/688efd52-d4de-4c38-8185-fd7a35a2192a)

I think it looks good, do you think it's ready or should I change anything?

**Comment by MenacingPerson** [comment]
I don't know the slightest about graphics design. This is fine, though!

**Comment by intergrav** [comment]
the full-size exports are now available in the art repo :>

**Comment by MenacingPerson** [comment]
https://github.com/skywardmc/art/issues/1
